language: rust
rust:
- nightly
- stable
cache: cargo

script:
- cargo build --verbose
- cargo test --verbose
- cargo build --verbose --no-default-features
- cargo test --verbose --no-default-features
